try {
    timeout(time: 20, unit: 'MINUTES') {
        stage('Initialize') {
            echo 'Copying workspace files ...'
            stash 'workspace'
        }

        node('nodejs') {
            stage('Start') {
                openshift.withCluster() {
                    openshift.withProject() {
                        echo 'Building..'
                    }  
                }
            }
            stage('Create') {
                exws (extWorkspace) {
                    openshift.withCluster() {
                        openshift.withProject() {
                            unstash 'workspace'
                            openshift.create( openshift.process("-f", "release/dev/rollout-template.yaml", 
                                                "--param-file", "release/release.properties",
                                                "--param-file", "application.properties",
                                                "--ignore-unknown-parameters", "true",
                                                "|",
                                                ))
                                                
                            sh 'ls -lrst'
                        }
                    }
                }
            }
        }
    }
} catch (err) {
    echo "in catch block"
    echo "Caught: ${err}"
    currentBuild.result = 'FAILURE'
    throw err
}          