try {
    timeout(time: 20, unit: 'MINUTES') {
        node('master') {
            stage('Initialize') {
                echo 'Copying workspace files ...'
                echo "Parameters : ${GIT_REPO}"
                git(url:'https://github.com/SagarOnline/openshift-devops-helloworld-config.git'
                        , branch:'master')
                stash 'workspace'
            }
        }
        node('nodejs') {
            stage('Start') {
                openshift.withCluster() {
                    openshift.withProject() {
                        echo 'Building..'
                    }  
                }
            }
            stage('Create') {
                openshift.withCluster() {
                    openshift.withProject() {
                        sh 'ls -lrst'
                        unstash 'workspace'
                        openshift.create( openshift.process("-f", "release/dev/rollout-template.yaml", 
                                            "--param-file", "release/release.properties",
                                            "--param-file", "application.properties",
                                            "--ignore-unknown-parameters", "true"
                                            ))
                                            
                        
                    }
                }
            }
        }
    }
} catch (err) {
    echo "in catch block"
    echo "Caught: ${err}"
    currentBuild.result = 'FAILURE'
    throw err
}          