pipeline {
    agent none

    stages {

        stage('Promote') {
            agent{
                docker{
                    image 'openshift/origin-cli'
                    label 'docker-agent'
                }
            }
            steps {
                script{
                    sh 'ls -lrst'

                    def props = readProperties  file: 'application.properties'
                    

                    // Login to OpenShift Cluster
                    //TODO : Credentials are currently hardcoded for Demo, these should be parameterized
                    sh "oc login $props.OPENSHIFT_CLUSTER_URL -u developer -p developer  --insecure-skip-tls-verify"

                    def devProjectName = "$props.APP_NAME-$props.RELEASE_NAME-dev"
                    echo "Promoting  application '$devProjectName' in DEV environment to IT"
                    sh "oc get project > projects.txt"
                    if (!readFile("projects.txt").contains(devProjectName)){
                        error("Project : " + devProjectName +" is not avialable in DEV environment. Nothing to promote !")
                        //Create Project for Application in Dev environment
                        //sh "oc new-project $props.APP_NAME-$props.RELEASE_NAME-dev"
                    }else {
                        def itProjectName = "$props.APP_NAME-$props.RELEASE_NAME-it"
                        if (!readFile("projects.txt").contains(itProjectName)){
                        }else{

                        }
                        //switch to existing project
                        sh "oc project $props.APP_NAME-$props.RELEASE_NAME-dev"
                    }

                    sh "oc get dc > deployments.txt"
                    if (!readFile("deployments.txt").contains("jenkins")){
                        // Run Jenkins pod to run OpenShift pipelines
                        sh 'oc new-app jenkins-ephemeral'
                    }

                    // Apply Resource object configuration changes
                    
                    sh 'oc process -f dev/pipelines/rollout/application-template.yaml --param-file application.properties --ignore-unknown-parameters=true | oc apply -f -'
                }
            }
        }
    }
}